<p><img alt="Colaboratory logo" height="140px" src="https://upload.wikimedia.org/wikipedia/commons/archive/f/fb/20161010213812%21Escudo-UdeA.svg" align="left" hspace="10px" vspace="0px"></p>

<h1> Diplomado de Análisis de datos y Machine Learning en Python</h1>


El presente diplomado hace parte del centro de Big Data de la facultad de ciencias exactas y naturales (FCEN) de la Universidad de Antioquia.

# Sesión 2

<p><a name="contents"></a></p>

# Contenido 

- <a href="#fun">1. Funciones y clases</a><br>
- <a href="#mod">2. Módulos</a><br>
- <a href="#num">3. Numpy</a><br>


# 1. Funciones y Clases.

## 1.1 Funciones.

Hasta ahora, nuestros scripts han sido bloques de código simples y de un solo uso. Una forma de organizar nuestro código de Python y hacerlo más legible y reutilizable es descomponer piezas útiles en funciones reutilizables. Las funciones son bloques de código que tienen un nombre y pueden ser llamadas usando paréntesis. Hemos visto funciones antes. Por ejemplo, `print()` es una función:

In [0]:
print("abc")

abc


aquí `print` es el nombre de la función, y `"abc"` es el *argumento* de la función. Adicionalmente, existen los *argumentos por palabra clave* (keyword arguments o kwargs) que se especifican por el nombre. Por ejemplo, un kwarg disponible para la función `print` es `end` que controla qué caracter añadir al final del último valor  

In [0]:
print(1, 2, 3, end = ".")

1 2 3.

o el kwarg `sep`, que controla qué caracter utilizar para separar los diferentes valores

In [0]:
print(1, 2, 3, sep = ",")

1,2,3


Cuando se usan argumentos que no son palabras clave junto con argumentos de palabras clave, los argumentos de palabras clave deben aparecer al final.


In [0]:
print(1, 2, sep = "", 3)

## Definiendo una función

Las funciones se vuelven aún más útiles cuando comenzamos a definir las nuestras. La sintáxis general para crear una función es la siguiente

>  

    def Funcion( parametros ):

            sentencia(s) 
            
            return [expresion]
    
     
* Los bloques de funciones comienzan con la palabra clave `def` seguida del nombre de la función y paréntesis ().
* Cualquier parámetro o argumento de entrada debe colocarse entre los paréntesis.
* El bloque de código dentro de cada función comienza con dos puntos (:) y está indentado.
* La declaración `return [expresion]` termina la función, opcionalmente devuelve una expresión al llamar la función.

Podemos definir una función que no tome ningún parámetro ni devuelva ningún valor:

In [0]:
def Hola():
    print("Hola mundo")
    return

O que sí tome argumentos pero no devuelva ningún valor

In [0]:
def Info(nombre, edad):
    print(f"Nombre: {nombre}")
    print(f"Edad: {edad}")
    return 

Ahora que hemos definido las funciones `Info` y `Hola`, podemos ejecutarlas en cualquier lugar del código (incluso dentro de otra función)

In [0]:
Hola()

Hola mundo


In [0]:
Info("Carlos", 20)

Nombre:  Carlos
Edad:  20


Una función ejecutada es igual al valor del `return`. En los casos anteriores, al no tener ningúna expresión en el `return`, la ejecución de la función será del tipo `None` (tener solo `return` es equivalente a `return = None`).

Si, por ejemplo, la expresión en el `return` es un string, podemos tratar a la función ejecutada como un string (aplica para cualquier tipo de variable)

In [0]:
def Info2(nombre, edad):
    return nombre, edad

In [0]:
nombre, edad = Info2("Natalia", 24)

print(nombre.upper())
print(edad)

NATALIA
24


Podemos añadir una descripción de la función en la primera línea del bloque de la función (conocida como Docstring), a la que se puede acceder como: `Nombre_funcion.__doc__`

In [0]:
def Hola():
    """ Imprime Hola mundo """
    print("Hola mundo")
    return

Hola.__doc__

## Argumentos de la función

Podemos llamar una función utilizando los siguientes tipos de argumentos formales:

* Argumentos requeridos.
* Argumentos predeterminados.
* Argumentos de longitud variable.

### Argumentos requeridos

Los argumentos requeridos son argumentos pasados a una función, que tienen un carácter obligatorio y se dan en el **orden posicional correcto**. Aquí, el número de argumentos en la llamada a la función debe coincidir exactamente con la definición de la función

In [0]:
Info(20, "Angela")

Si los argumentos los pasamos como argumentos por palabra clave no importará el orden

In [0]:
Info(edad = "20", nombre = "Angela")

### **Argumentos predeterminados**

A menudo, al definir una función, hay ciertos valores que queremos que la función use la mayor parte del tiempo, pero también nos gustaría tener cierta flexibilidad en la elección de estos valores. En tal caso, podemos usar valores predeterminados para los argumentos.

In [0]:
def Info(nombre, edad = 20):
    print(f"Nombre: {nombre}")
    print(f"Edad: {edad}")
    return 

De esta manera, el argumento `edad` ya no es un argumento requerido

In [0]:
Info("Carlos")

Cuando en una función uno de sus argumentos lleva un valor por defecto, éste se convierte automáticamente en un kwarg, tal como un diccionario. Por lo tanto, puede ser especificado indicando su nombre al momento de llamar la función

In [0]:
Info("Carlos", edad = 25)

**Nota**: Si se define un kwarg para la función, todos los argumentos deben definirse antes de los kwargs.

In [0]:
def Info(edad = 20, nombre):
    print(f"Nombre: {nombre}")
    print(f"Edad: {edad}")
    return 

### **Argumentos de longitud variable**

Es posible que necesitemos ejecutar una función en la que en principio no sabemos cuántos argumentos se pasarán a la función. En este caso, podemos utilizar una clase especial de argumentos, denominados argumentos de longitud variable, con los que podemos capturar todos los argumentos que se pasen a la función.

El argumento de longitud variable `*args` permite capturar una serie de argumentos sin necesidad de especificar en un principio su número

In [0]:
def Print(*args):
    print(f"args: {args}")
    return

Print(1,2,3)

Lo importante aquí no es el nombre `args`, sino el caracter \* que lo precede. `args` es solo el nombre que se usa por convención. Un solo * antes de una variable significa **expandir esto como una secuencia**. De hecho, esta sintáxis puede utilizarse no solo en la definición de la función, sino también a la hora de llamar la función 

In [0]:
#pasando el argumento precedido por un *
lista = [1,2,3]

Print(*lista)

Note que esto se puede realizar incluso si la función no se definió con un argumento `*args`:

In [0]:
def Funcion(a,b):
    return a+b

lista = [1,2]
Funcion(*lista)

Al igual que con `*args`, podemos utilizar el argumento por longitud variable `*kwargs` para capturar un número indefinido de argumentos por palabra clave:

In [0]:
def Print(**kwargs):
    print("kwargs: ",kwargs)
    return

Print(nombre = "Camilo", edad = "25")

kwargs:  {'nombre': 'Camilo', 'edad': '25'}


Un doble ** antes de una variable significa **expandir esto como un diccionario**

In [0]:
dic = {"nombre": "Camilo", "edad": 25}

Print(**dic)

kwargs:  {'nombre': 'Camilo', 'edad': 25}


## Funciones Anónimas

Estas funciones se denominan anónimas porque no se declaran de la manera estándar utilizando la palabra clave `def`. Podemos usar la palabra clave `lambda` para crear pequeñas funciones anónimas. La sintáxis general es de la forma:

> `lambda arg1, arg2, ... : expresion`

In [0]:
suma = lambda x, y: x + y 

suma(1,1)

Lo que es equivalente a

In [0]:
def suma(x,y):
    return x+y

suma(1,1)

## 1.2 Clases

Las clases proporcionan un medio de agrupar datos y "funcionalidad". La creación de una nueva clase crea un nuevo tipo de objeto, lo que permite crear nuevas *instancias* de ese tipo. Cada instancia de la clase puede tener sus propios atributos. Las instancias de una clase también pueden tener *métodos* (definidos por su clase) para modificar su estado.

>
    class Nombre:
          sentencia(s)

Los atributos son como propiedades que queremos añadir a la clase. Adicionalmente, dentro de las clases podemos definir funciones, conocidas como **métodos**. Los métodos necesitan tener un argumento convenientemente llamado `self`, que se refiere al objeto del método que está siendo llamado. Podemos pasar más de un argumento si así lo deseamos

In [0]:
class Persona:
    nombre = ''
    edad = ''
     
    def print_informacion(self, nombre, edad):
        print(f'nombre: {self.nombre}')
        print(f'edad: {self.edad}')
             
carlos = Persona()
carlos.nombre = 'carlos'
carlos.edad = '30'
carlos.print_informacion(carlos.nombre, carlos.edad)

La operación de creación de instancias crea un objeto vacío. Podemos crear objetos con instancias personalizadas a un estado inicial específico utilizando un método especial llamado `__init __`

In [0]:
class Person:
  def __init__(self,n,e):
    self.nombre = n
    self.edad = e
      
mario = Person('mario','55')
print('nombre:',mario.nombre)
print('edad:',mario.edad)

# 2. Módulos

Una característica de Python que lo hace útil para una amplia gama de tareas es el hecho de que viene con "baterías incluidas", es decir, la [biblioteca estándar de Python](https://docs.python.org/3/library/) contiene herramientas útiles para una amplia gama de tareas. Además de esto, hay un amplio ecosistema de herramientas y paquetes de terceros que ofrecen una funcionalidad más especializada.

Para importar módulos de Python o de terceros, utilizamos la palabra clave `import`. Esta puede ser utilizada de varias maneras. Trabajemos con el módulo `math`, que contiene una serie de funciones matemáticas.

In [0]:
#importar el modulo explicitamente
import math

La función incorporada `dir()` devuelve una lista ordenada que contiene los nombres definidos por un módulo. La lista contiene los nombres de todas las variables y funciones que se definen en un módulo.

In [0]:
dir(math)

Recordemos que en Python todo es un objeto, por lo que para acceder a los métodos (funciones) del objeto `math` utilizamos el operador `(.)`

Para obtener una descripción detallada de alguna función de la librería utilizamos la función `help`

In [0]:
help(math.cos)

O utilizar el símbolo `?`

In [0]:
?math.cos

In [0]:
math.cos(math.pi)

Podemos exportar el módulo explícitamente con un "alias"


In [0]:
import math as m

m.cos(m.pi)

Alternativamente, podemos exportar todo el módulo, o solo algunas de sus funciones, de manera implícita

In [0]:
from math import *

cos(pi)

In [0]:
from math import sqrt

sqrt(2)

Para importar paquetes de terceros la sintáxis es la misma, solo que primero tenemos que instalar los módulos en nuestra máquina o entorno. En Google Colab, la mayoría de paquetes de terceros vienen instalados por defecto.

# 3. NumPy

En el núcleo de la mayoría de los problemas encontramos un **arreglo**. Desde el punto de vista computacional, un arreglo es un bloque contiguo de memoria donde cada elemento tiene el mismo tipo.

Los diferentes lenguajes de programación utilizados en computación científica tienen alguna noción de manejo de datos basado en arreglos, ya sea integrado en el lenguaje propio o a través de paquetes proporcionados por terceros.

NumPy (Numerical Python) es el paquete fundamental para la computación científica en Python. Es una libreria de Python que proporciona herramientas para la generación de arreglos y una variedad de funcionalidades para realizar operaciones sobre estos, que generalmente se realizan de una manera más eficiente que lo que se puede lograr con funcionalidades propias de Python. NumPy sirve como bloque básico para una gran cantidad de paquetes científicos y de análisis de datos.

## Arreglos en NumPy

La implementación estándar de Python está escrita en C. Esto significa que cada objeto de Python es simplemente una estructura de C, que contiene no solo su valor, sino también otra información. Por ejemplo, cuando definimos un número entero en Python, como $x = 10000$, $x$ no es solo un número entero "en bruto". En realidad, es un puntero a una estructura compuesta de C, que contiene cuatro valores diferentes: referencia, tipo, tamaño y valor.

<p><img alt="Colaboratory logo" height="150px" src="https://i.imgur.com/qSGYNQe.png" align="left" hspace="10px" vspace="0px"></p>

Recordemos que en Python, al ser un lenguaje de tipado dinámico, podemos generar listas donde cada uno de sus elementos pueden ser de cualquier tipo

In [0]:
L = [True, "2", 3.0, 4]

[type(i) for i in L]

[bool, str, float, int]

Recordemos que esta flexibilidad tiene un costo: cada elemento de la lista debe contener su propia información, es decir, cada elemento es un objeto completo de Python. En el caso especial en que todas las variables sean del mismo tipo, gran parte de esta información es redundante: puede ser mucho más eficiente almacenar datos en un arreglo de tipo homogéneo. Python ofrece diferentes opciones para almacenar datos de esta manera (por ejemplo a través del módulo `array`). Sin embargo, la mejor manera de generar este tipo de objetos es a través de la libreria NumPy.

En el núcleo de NumPy, está el objeto `ndarray` (n-dimensional array). Este encapsula arreglos n-dimensionales de tipos de datos homogéneos, con muchas operaciones que se realizan en código compilado, con lo cual se mejora el rendimiento significativamente. La diferencia entre una lista de tipo dinámico y un arreglo de tipo fijo (al estilo NumPy) se ilustra en la siguiente figura:

<p><img alt="Colaboratory logo" height="350px" src="https://i.imgur.com/8EbyB0c.png" align="left" hspace="10px" vspace="0px"></p>


Al nivel de implementación, el arreglo contiene esencialmente un puntero único a un bloque contiguo de datos. La lista de Python, por otro lado, contiene un puntero a un bloque de punteros, cada uno de los cuales a su vez apunta a un objeto completo de Python como el entero de Python que vimos anteriormente.

En resumen, estas son las diferencias más importantes entre los arreglos de NumPy y las secuencias estándar de Python:

* Todos los elementos en un arreglo de NumPy deben ser del mismo tipo de datos y, por lo tanto, tendrán el mismo tamaño en memoria.
* Los arreglos de NumPy tienen un tamaño fijo en la creación, a diferencia de las listas de Python (que pueden crecer dinámicamente). Cambiar el tamaño de un `ndarray` creará un nuevo arreglo y eliminará el original.
* Los arreglos de NumPy facilitan operaciones avanzadas matemáticas y de otro tipo en grandes cantidades de datos. Típicamente, tales operaciones se ejecutan de manera más eficiente que usando las secuencias integradas de Python.
* Una creciente cantidad de paquetes científicos y matemáticos basados ​​en Python están utilizando arreglos de NumPy

## Creando arreglos con NumPy

En lugar de crearse directamente, los `ndarrays` a menudo se instancian a través de la función `array()` que también proporciona NumPy. Para crear un arreglo, importamos NumPy y llamamos a la función `array()` en una secuencia de Python. 

Por convención, el paquete NumPy se importa con el alias `np`:

In [0]:
import numpy as np

#crear arreglo a partir de una lista de Python
a = np.array([1, 2, 3, 4])

print(a, type(a))

[1 2 3 4] <class 'numpy.ndarray'>


NumPy proporciona varias formas de crear arreglos además de la función normal `array()`. Las cinco funciones más comunes son `arange()`, `zeros()`, `ones()`, `full()` y `empty()`. 

La función `arange()` toma un inicio, final y un paso exactamente igual a la función `range()` de Python, excepto que devuelve un `ndarray`:

In [0]:
#crear un arreglo de manera similar a la funcion range()
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

Las funciones `zeros()` y `ones()` toman un entero o una tupla de enteros como argumento y devuelven un `ndarray` cuya forma coincide con la de la tupla y cuyos elementos son cero o uno:

In [0]:
#crear un arreglo de 5 elementos llenado con ceros
np.zeros(5)

In [0]:
#crear un arreglo de dimension 2x2 llenado con ceros
np.zeros((2,2))

In [0]:
#crear un arreglo de 5 elementos llenado con unos
np.ones(5)

array([1., 1., 1., 1., 1.])

In [0]:
#crear un arreglo de dimension 2x2 llenado con unos
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

La función `full()` funciona de manera similar a `zeros()` y `ones()`, solo que podemos llenar el arreglo con cualquier valor:

In [0]:
#crear un arreglo 2x2 llenado con pi
np.full((2,2), np.sin(np.pi))

array([[1.2246468e-16, 1.2246468e-16],
       [1.2246468e-16, 1.2246468e-16]])

La función `empty()`, por otro lado, simplemente asignará memoria sin asignarle ningún valor. Esto significa que el contenido de un arreglo vacío será lo que esté en la memoria en ese momento.

In [0]:
#crear un arreglo vacio de 4 elementos 
np.empty(4)

array([1., 1., 1., 0.])

También es importante conocer la función `linspace()`. Esta crea una grilla de puntos uniformemente lineal entre un límite inferior y superior que incluye ambos extremos. Su sintáxis es de la forma:

> 
    np.linspace(inicio, final, número de puntos)

In [0]:
np.linspace(0, 1, 10)

## Atributos de los arreglos de Numpy

Para todos estos mecanismos de creación de arreglos, el objeto `ndarray` representa efectivamente un bloque de memoria de tamaño fijo y metadatos (información acerca de la estructura de datos) que definen las características del arreglo. 

###  dtype: 

El tipo de dato (data type) es el atributo más importante. Este determina el tamaño y el significado de cada elemento del arreglo. El sistema predeterminado de dtypes que proporciona NumPy es más preciso y más amplio para los tipos básicos que el sistema de tipos que implementa el lenguaje Python

### shape: 

Tupla de enteros que representa el rango a lo largo de cada dimensión.

In [0]:
a = np.zeros((2, 2))

a.shape

(2, 2)

NumPy proporciona la función `reshape()`, con la cual podemos cambiar la forma de un arreglo. Esta toma como argumento el arreglo a modificar y un entero o tupla que represente la nueva forma

In [0]:
a = np.arange(4)

b = np.reshape(a, (2, 2))

print(a)
print(b)

[0 1 2 3]
[[0 1]
 [2 3]]


El criterio a cumplir para proporcionar la nueva forma es que esta **debe ser compatible con la forma original**.

Otros atributos útiles son:

* `ndim`: Número de dimensiones (`int`).

* `size`: Número total de elementos (`int`), igual al producto de todos los elementos de `shape`.

In [0]:
a = np.arange(1, 10).reshape((3, 3))  

print(a)
print("Número de dimensiones: ",a.ndim)
print("Número total de elementos: ",a.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Número de dimensiones:  2
Número total de elementos:  9


## Indexación y segmentación

Los arreglos de NumPy tienen la misma semántica de indexación y segmentación que las listas de Python cuando se trata de acceder a elementos o subarreglos:


> `arreglo[inicio:final:paso]` 

In [0]:
a = np.arange(8)

print("a:\n",a)

print("a[2:6]:\n",a[2:6])

print("a[1::3]:\n",a[1::3])

print("a[::-1]:\n",a[::-1])

En NumPy, en lugar de indexar por un segmento, podemos indexar por una tupla de segmentos, cada uno de los cuales actúa en sus propias dimensiones:

In [0]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
S = a[:,0:2]
S

array([[1, 2],
       [4, 5],
       [7, 8]])

Los ciclos `for` para la segmentación multidimensional son manejados implícitamente por NumPy. Esto hace que ejecutar cortes complejos sea mucho más rápido que escribir los ciclos `for` explícitamente en Python. Si un eje se deja fuera de una segmentación multidimensional, se incluyen todos los elementos a lo largo de esa dimensión. También tenga en cuenta que las filas van antes que las columnas en NumPy. Veamos algunos ejemplos:

In [0]:
#creamos un arreglo de dimensiones 4x4
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [0]:
#segmentar las filas pares y las columnas impares.
a[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [0]:
#segmentar la matriz interna de 2x2.
a[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [0]:
#invertir las primeras 3 filas, tomando las primeras 3 columnas
a[2::-1, :3]

array([[ 8,  9, 10],
       [ 4,  5,  6],
       [ 0,  1,  2]])

In [0]:
#seleccionar la primer fila (equivalente a a[0,:])
a[0]

array([0, 1, 2, 3])

La característica más importante de la segmentación de arreglos es que las segmentaciones son *vistas* del arreglo original (No se copian datos cuando se realiza una segmentación, lo que hace que NumPy sea especialmente rápido para las operaciones de segmentación). Si realmente deseamos una copia de una segmentación de un arreglo, siempre podemos crear un nuevo arreglo a partir de esta segmentación de la siguiente manera:

In [0]:
a = np.arange(5)

b = np.array(a[1::2])

b[1] = 42

print("a: ",a)
print("b: ",b)

a:  [0 1 2 3 4]
b:  [ 1 42]


También se puede utilizar el método `copy()` de la siguiente manera:

In [0]:
a = np.arange(5)

b = a[1::2].copy()

b[1] = 42

print("a: ",a)
print("b: ",b)

a:  [0 1 2 3 4]
b:  [ 1 42]


# Operaciones sobre los arreglos

Ahora que hemos visto cómo definir y manipular arreglos, podemos discutir cómo transformarlos. El computo sobre arreglos en NumPy puede ser muy rápido o muy lento. La clave para hacerlo rápido es usar operaciones *vectorizadas*, generalmente implementadas a través de las funciones universales de NumPy (ufuncs)

Supongamos que tenemos un arreglo de valores para los cuales queremos calcular el recíproco. Un primer método en el que pensariamos sería utilizando un ciclo `for` de la siguiente manera:

In [0]:
def Reciproco(valores):
  """ Función que calcula el recíproco para cada elemento en un arreglo """

  salida = np.empty(len(valores))

  for i in range(len(valores)):
    salida[i] = 1.0 / valores[i]
    
  return salida

a = np.array([1, 2, 3])

Reciproco(a)

array([1.        , 0.5       , 0.33333333])

Si medimos el tiempo de ejecución de este código para un arreglo "grande", vemos que esta operación es muy lenta

In [0]:
a = np.arange(1,10000000)

%timeit Reciproco(a)

¡Toma varios segundos calcular estos millones de operaciones y almacenar el resultado! Resulta que el cuello de botella aquí no son las operaciones en sí mismas, sino la verificación de tipos y demás que Python debe hacer en cada ciclo. Cada vez que se calcula el recíproco, Python primero examina el tipo de objeto y realiza una búsqueda dinámica de la función correcta que se utilizará para ese tipo. Si estuviéramos trabajando en código compilado, esta especificación de tipo se conocería antes de que se ejecute el código y el resultado podría calcularse de manera mucho más eficiente.

## Introduciendo las funciones universales (ufuncs)

Para muchos tipos de operaciones, NumPy proporciona una interfaz conveniente de rutina compilada de tipo estático. Esto se conoce como una operación *vectorizada*. En el contexto de lenguajes de alto nivel como Python, el término **vectorización** representa el uso de código optimizado y precompilado escrito en lenguajes de bajo nivel (por ejemplo C) para realizar operaciones matemáticas en una secuencia de datos. Esto se realiza en lugar de una iteración explicita escrita en código nativo.

Comparemos el tiempo de cómputo con el resultado anterior, esta vez utilizando una operación vectorizada:

In [0]:
a = np.arange(1,10000000)

%timeit 1/a

Las operaciones vectorizadas en NumPy se implementan a través de las ufuncs, cuyo objetivo principal es ejecutar rápidamente operaciones repetidas sobre los valores en los arreglos de NumPy. En la celda anterior vimos una operación entre un entero y un arreglo, pero también podemos realizar operaciones entre arreglos:

In [0]:
np.arange(5)/np.arange(1,6)

Además, estas operaciones no están restringidas para arreglos unidimensionales. Podemos realizar este tipo de operaciones obre arreglos multidimensionales:

In [0]:
2 * np.arange(9).reshape((3, 3))

Los cálculos que usan vectorización a través de ufuncs son casi siempre más eficientes que su contraparte implementada a través de ciclos, especialmente a medida que los arrays crecen en tamaño. Cada vez que se vea un ciclo de este tipo en un script de Python, debe considerarse si este puede reemplazarse con una expresión vectorizada.

Todas estas operaciones aritméticas son simplemente "envolturas" convenientes alrededor de funciones específicas integradas en NumPy; por ejemplo, el operador `+` es un contenedor para la función `np.add()`:

In [0]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

# Suma elemento a elemento
print("a+b: \n",np.add(a, b))

# Resta elemento a elemento.
print("a-b: \n",np.subtract(a, b))

# Multiplicación elemento a elemento.
print("a*b: \n",np.multiply(a, b))

# División elemento a elemento.
print("a/b: \n",np.divide(a, b))

# Enmascaramiento 

Veamos el uso de máscaras booleanas para examinar y manipular valores dentro de los arreglos de NumPy. El enmascaramiento aparece cuando deseamos extraer, modificar, o manipular valores en un arreglo de acuerdo con algún criterio.

La sesión anterior vimos cómo utilizar ufuncs para operaciones aritméticas básicas y otro tipo de operaciones más complejas. NumPy implementa también operadores de comparasión como ufuncs:

In [0]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [0]:
x < 5

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

El resultado es un arreglo booleano. Dado un arreglo booleano, hay una serie de operaciones útiles que podemos implementar. 

Podemos utilizar la función `np.sum()` junto con los operadores de comparación para realizar conteos dentro del arreglo:

In [0]:
# numero de elementos menores a 6
np.sum(x < 6)

Con `np.sum()` podemos realizar este tipo de conteos a lo largo de las filas o columnas, utilizando el argumento por palabra clave `axis`:

In [0]:
# numero de elementos menores a 6 por columna
np.sum(x < 6, axis=0)

array([2, 2, 2])

In [0]:
# numero de elementos menores a 6 por fila
np.sum(x < 6, axis=1)

array([3, 3, 0])

Podemos también tener múltiples condiciones en un conteo, utilizando los operadores lógicos `&` (and) y `|` (or)

In [0]:
# verdadero si ambos verdaderos
np.sum((x > 1) & (x < 5))

3

In [0]:
# verdadero en caso en que alguno de los dos sea verdadero
np.sum((x > 6) | (x < 2))

Una herramienta muy poderosa es usar los arreglos booleanos como máscaras, para seleccionar subconjuntos particulares de los datos mismos. Volviendo a nuestra arreglo `x` anterior, supongamos que queremos un arreglo de todos los valores en `x` que sean menores que, digamos, 5. Para seleccionar estos valores del arreglo, simplemente podemos indexar con este arreglo booleano; esto se conoce como una operación de enmascaramiento:

In [0]:
x[x < 5]

array([0, 1, 2, 3, 4])

Lo que se devuelve es un arreglo unidimensional con todos los valores que cumplen la condición; en otras palabras, todos los valores en las posiciones en las que el arreglo de máscara es `True`.

## **Ejercicio**: Escriba un programa para crear un nuevo arreglo que sea el promedio de cada triplete consecutivo de elementos del siguiente arreglo

<p><img alt="Colaboratory logo" height="70px" src="https://i.imgur.com/XoHovZd.png" align="left" hspace="10px" vspace="0px"></p>